#############################################################################
# Makefile for building: LinkScope.app/Contents/MacOS/LinkScope
# Generated by qmake (3.1) (Qt 5.15.19)
# Project:  LinkScope.pro
# Template: app
# Command: /opt/homebrew/Cellar/qt@5/5.15.19/bin/qmake -o Makefile LinkScope.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Library/Developer/CommandLineTools/usr/bin/clang
CXX           = /Library/Developer/CommandLineTools/usr/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DAPP_VERSION=\"1.3.0\" -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_SERIALPORT_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.13 -Wall -Wextra -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.13 -Wall -Wextra -fPIC $(DEFINES)
INCPATH       = -I. -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtGui.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtNetwork.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtSerialPort.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers -I. -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I. -I/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/macx-clang -F/opt/homebrew/Cellar/qt@5/5.15.19/lib
QMAKE         = /opt/homebrew/Cellar/qt@5/5.15.19/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /opt/homebrew/Cellar/qt@5/5.15.19/bin/qmake -install qinstall
QINSTALL_PROGRAM = /opt/homebrew/Cellar/qt@5/5.15.19/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = LinkScope1.0.0
DISTDIR = /Users/chenyouyuan/cyy_ws/LinkScope/.tmp/LinkScope1.0.0
LINK          = /Library/Developer/CommandLineTools/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.13 -Wl,-rpath,@executable_path/../Frameworks
LIBS          = $(SUBLIBS) -F/opt/homebrew/Cellar/qt@5/5.15.19/lib -framework QtWidgets -framework QtGui -framework AppKit -framework Metal -framework QtNetwork -framework QtSerialPort -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL   
AR            = /Library/Developer/CommandLineTools/usr/bin/ar cq
RANLIB        = /Library/Developer/CommandLineTools/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = aboutwindow.cpp \
		configwindow.cpp \
		gdbprocess.cpp \
		graphwindow.cpp \
		helpwindow.cpp \
		listwindow.cpp \
		logwindow.cpp \
		main.cpp \
		mainwindow.cpp \
		openocd.cpp \
		serialocd.cpp qrc_res.cpp \
		moc_aboutwindow.cpp \
		moc_configwindow.cpp \
		moc_gdbprocess.cpp \
		moc_graphwindow.cpp \
		moc_helpwindow.cpp \
		moc_listwindow.cpp \
		moc_logwindow.cpp \
		moc_mainwindow.cpp \
		moc_openocd.cpp \
		moc_serialocd.cpp
OBJECTS       = aboutwindow.o \
		configwindow.o \
		gdbprocess.o \
		graphwindow.o \
		helpwindow.o \
		listwindow.o \
		logwindow.o \
		main.o \
		mainwindow.o \
		openocd.o \
		serialocd.o \
		qrc_res.o \
		moc_aboutwindow.o \
		moc_configwindow.o \
		moc_gdbprocess.o \
		moc_graphwindow.o \
		moc_helpwindow.o \
		moc_listwindow.o \
		moc_logwindow.o \
		moc_mainwindow.o \
		moc_openocd.o \
		moc_serialocd.o
DIST          = /opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/spec_pre.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/qdevice.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/device_config.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/common/unix.conf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/common/mac.conf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/common/macx.conf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/common/sanitize.conf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/common/gcc-base.conf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/common/gcc-base-mac.conf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/common/clang.conf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/common/clang-mac.conf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/qconfig.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3danimation.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3danimation_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dextras.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dextras_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquickextras.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3drender.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_charts.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_core.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_core_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_datavisualization.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_dbus.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_designer.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_edid_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_gamepad.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_gamepad_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_gui.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_help.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_help_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_location.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_location_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_macextras.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_macextras_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_network.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_network_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_networkauth.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_networkauth_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_nfc.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_opengl.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_positioning.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_positioningquick.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_purchasing.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_purchasing_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qml.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qmlmodels.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick3d.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick3d_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick3drender.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick3drender_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick3dutils.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_remoteobjects.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_repparser.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_repparser_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_script.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_script_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_scxml.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_scxml_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_sensors.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_serialport.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_service_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_sql.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_svg.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_testlib.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_texttospeech.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_theme_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_uitools.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_websockets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_webview.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_widgets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_xml.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/qt_functions.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/qt_config.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/macx-clang/qmake.conf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/exclusive_builds.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/mac/sdk.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/toolchain.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/mac/toolchain.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/default_pre.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/mac/default_pre.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/resolve_config.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/default_post.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/mac/default_post.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/mac/objective_c.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/mac/mac.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/warn_on.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/qt.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/resources_functions.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/resources.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/moc.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/unix/opengl.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/uic.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/unix/thread.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/qmake_use.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/file_copies.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/mac/rez.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/mac/asset_catalogs.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/testcase_targets.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/exceptions.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/yacc.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/lex.prf \
		LinkScope.pro aboutwindow.h \
		configwindow.h \
		gdbprocess.h \
		graphwindow.h \
		helpwindow.h \
		listwindow.h \
		logwindow.h \
		mainwindow.h \
		openocd.h \
		serialocd.h \
		vartype.h aboutwindow.cpp \
		configwindow.cpp \
		gdbprocess.cpp \
		graphwindow.cpp \
		helpwindow.cpp \
		listwindow.cpp \
		logwindow.cpp \
		main.cpp \
		mainwindow.cpp \
		openocd.cpp \
		serialocd.cpp
QMAKE_TARGET  = LinkScope
DESTDIR       = 
TARGET        = LinkScope.app/Contents/MacOS/LinkScope

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 26.2
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Library/Developer/CommandLineTools
EXPORT__QMAKE_STASH_ = /Users/chenyouyuan/cyy_ws/LinkScope/.qmake.stash
EXPORT_VALID_ARCHS = arm64
EXPORT_DEFAULT_ARCHS = arm64
EXPORT_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(if $(ARCHS), $(ARCHS), $(if $(EXPORT_DEFAULT_ARCHS), $(EXPORT_DEFAULT_ARCHS), $(EXPORT_VALID_ARCHS))))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ARCHS), $(EXPORT_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/chenyouyuan/cyy_ws/LinkScope/LinkScope.pro


include /opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

LinkScope.app/Contents/MacOS/LinkScope: ui_aboutwindow.h ui_configwindow.h ui_graphwindow.h ui_helpwindow.h ui_listwindow.h ui_logwindow.h ui_mainwindow.h $(OBJECTS)  
	@test -d LinkScope.app/Contents/MacOS/ || mkdir -p LinkScope.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: LinkScope.pro /opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/macx-clang/qmake.conf /opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/spec_pre.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/qdevice.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/device_config.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/common/unix.conf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/common/mac.conf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/common/macx.conf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/common/sanitize.conf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/common/gcc-base.conf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/common/gcc-base-mac.conf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/common/clang.conf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/common/clang-mac.conf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/qconfig.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3danimation.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3danimation_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dextras.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dextras_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquickextras.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3drender.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_charts.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_core.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_core_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_datavisualization.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_dbus.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_designer.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_edid_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_gamepad.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_gamepad_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_gui.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_help.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_help_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_location.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_location_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_macextras.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_macextras_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_network.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_network_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_networkauth.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_networkauth_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_nfc.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_opengl.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_positioning.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_positioningquick.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_purchasing.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_purchasing_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qml.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qmlmodels.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick3d.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick3d_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick3drender.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick3drender_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick3dutils.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_remoteobjects.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_repparser.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_repparser_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_script.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_script_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_scxml.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_scxml_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_sensors.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_serialport.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_service_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_sql.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_svg.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_testlib.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_texttospeech.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_theme_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_uitools.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_websockets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_webview.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_widgets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_xml.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/qt_functions.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/qt_config.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/macx-clang/qmake.conf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/exclusive_builds.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/mac/sdk.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/toolchain.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/mac/toolchain.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/default_pre.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/mac/default_pre.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/resolve_config.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/default_post.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/mac/default_post.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/mac/objective_c.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/mac/mac.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/warn_on.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/qt.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/resources_functions.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/resources.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/moc.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/unix/opengl.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/uic.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/unix/thread.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/qmake_use.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/file_copies.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/mac/rez.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/mac/asset_catalogs.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/testcase_targets.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/exceptions.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/yacc.prf \
		/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/lex.prf \
		LinkScope.pro \
		res.qrc \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtGui.framework/Resources/QtGui.prl \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtNetwork.framework/Resources/QtNetwork.prl \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtSerialPort.framework/Resources/QtSerialPort.prl \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Makefile LinkScope.pro
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/spec_pre.prf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/qdevice.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/device_config.prf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/common/unix.conf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/common/mac.conf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/common/macx.conf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/common/sanitize.conf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/common/gcc-base.conf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/common/gcc-base-mac.conf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/common/clang.conf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/common/clang-mac.conf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/qconfig.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3danimation.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3danimation_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dcore.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dcore_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dextras.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dextras_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dinput.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dinput_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dlogic.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dlogic_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquick.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquick_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquickanimation.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquickextras.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquickinput.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquickrender.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3drender.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_3drender_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_bodymovin_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_charts.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_charts_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_clipboard_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_concurrent.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_core.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_core_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_datavisualization.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_datavisualization_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_dbus.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_designer.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_designer_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_designercomponents_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_edid_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_fb_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_gamepad.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_gamepad_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_graphics_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_gui.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_gui_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_help.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_help_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_location.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_location_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_macextras.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_macextras_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_multimedia.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_network.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_network_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_networkauth.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_networkauth_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_nfc.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_opengl.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_positioning.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_positioningquick.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_positioningquick_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_printsupport.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_purchasing.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_purchasing_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qml.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qml_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qmldebug_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qmlmodels.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qmltest.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick3d.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick3d_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick3dassetimport.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick3drender.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick3drender_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick3druntimerender.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick3dutils.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick3dutils_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quick_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quickcontrols2.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quickshapes_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quicktemplates2.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_remoteobjects.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_repparser.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_repparser_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_script.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_script_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_scripttools.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_scripttools_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_scxml.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_scxml_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_sensors.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_serialbus.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_serialbus_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_serialport.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_service_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_sql.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_sql_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_svg.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_svg_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_testlib.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_texttospeech.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_texttospeech_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_theme_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_uiplugin.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_uitools.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_webchannel.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_webchannel_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_websockets.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_webview.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_webview_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_widgets.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_xml.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_xml_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/qt_functions.prf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/qt_config.prf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/macx-clang/qmake.conf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/spec_post.prf:
.qmake.stash:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/exclusive_builds.prf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/mac/sdk.prf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/toolchain.prf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/mac/toolchain.prf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/default_pre.prf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/mac/default_pre.prf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/resolve_config.prf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/default_post.prf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/mac/default_post.prf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/mac/objective_c.prf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/mac/mac.prf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/warn_on.prf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/qt.prf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/resources_functions.prf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/resources.prf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/moc.prf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/unix/opengl.prf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/uic.prf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/unix/thread.prf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/qmake_use.prf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/file_copies.prf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/mac/rez.prf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/mac/asset_catalogs.prf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/testcase_targets.prf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/exceptions.prf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/yacc.prf:
/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/lex.prf:
LinkScope.pro:
res.qrc:
/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Resources/QtWidgets.prl:
/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtGui.framework/Resources/QtGui.prl:
/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtNetwork.framework/Resources/QtNetwork.prl:
/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtSerialPort.framework/Resources/QtSerialPort.prl:
/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile LinkScope.pro

qmake_all: FORCE

LinkScope.app/Contents/PkgInfo: 
	@test -d LinkScope.app/Contents || mkdir -p LinkScope.app/Contents
	@$(DEL_FILE) LinkScope.app/Contents/PkgInfo
	@echo "APPL????" > LinkScope.app/Contents/PkgInfo
LinkScope.app/Contents/Resources/empty.lproj: 
	@test -d LinkScope.app/Contents/Resources || mkdir -p LinkScope.app/Contents/Resources
	@touch LinkScope.app/Contents/Resources/empty.lproj
	
LinkScope.app/Contents/Info.plist: 
	@test -d LinkScope.app/Contents || mkdir -p LinkScope.app/Contents
	@$(DEL_FILE) LinkScope.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.LinkScope,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},com.yourcompany.LinkScope,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.13,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,LinkScope,g" -e "s,@LIBRARY@,LinkScope,g" -e "s,\$${EXECUTABLE_NAME},LinkScope,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" /opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/macx-clang/Info.plist.app >LinkScope.app/Contents/Info.plist

all: Makefile \
		LinkScope.app/Contents/PkgInfo \
		LinkScope.app/Contents/Resources/empty.lproj \
		LinkScope.app/Contents/Info.plist LinkScope.app/Contents/MacOS/LinkScope

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents res.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents aboutwindow.h configwindow.h gdbprocess.h graphwindow.h helpwindow.h listwindow.h logwindow.h mainwindow.h openocd.h serialocd.h vartype.h $(DISTDIR)/
	$(COPY_FILE) --parents aboutwindow.cpp configwindow.cpp gdbprocess.cpp graphwindow.cpp helpwindow.cpp listwindow.cpp logwindow.cpp main.cpp mainwindow.cpp openocd.cpp serialocd.cpp $(DISTDIR)/
	$(COPY_FILE) --parents aboutwindow.ui configwindow.ui graphwindow.ui helpwindow.ui listwindow.ui logwindow.ui mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r LinkScope.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)"

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_res.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_res.cpp
qrc_res.cpp: res.qrc \
		/opt/homebrew/Cellar/qt@5/5.15.19/bin/rcc \
		icon.ico \
		qss/light-blue.qss \
		qss/qss-img/light-blue-radiobutton-unchecked.png \
		qss/qss-img/light-blue-checkbox-checked.png \
		qss/qss-img/light-blue-checkbox-unchecked.png \
		qss/qss-img/light-blue-tree-open.png \
		qss/qss-img/light-blue-radiobutton-checked.png \
		qss/qss-img/light-blue-uparrow.png \
		qss/qss-img/light-blue-downarrow.png \
		qss/qss-img/light-blue-tree-vline.png \
		qss/qss-img/light-blue-tree-end.png \
		qss/qss-img/light-blue-tree-closed.png \
		qss/qss-img/light-blue-tree-more.png
	/opt/homebrew/Cellar/qt@5/5.15.19/bin/rcc -name res res.qrc -o qrc_res.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/data/dummy.cpp
	/Library/Developer/CommandLineTools/usr/bin/clang++ -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.13 -Wall -Wextra -dM -E -o moc_predefs.h /opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_aboutwindow.cpp moc_configwindow.cpp moc_gdbprocess.cpp moc_graphwindow.cpp moc_helpwindow.cpp moc_listwindow.cpp moc_logwindow.cpp moc_mainwindow.cpp moc_openocd.cpp moc_serialocd.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_aboutwindow.cpp moc_configwindow.cpp moc_gdbprocess.cpp moc_graphwindow.cpp moc_helpwindow.cpp moc_listwindow.cpp moc_logwindow.cpp moc_mainwindow.cpp moc_openocd.cpp moc_serialocd.cpp
moc_aboutwindow.cpp: aboutwindow.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QDialog \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qdialog.h \
		moc_predefs.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/bin/moc
	/opt/homebrew/Cellar/qt@5/5.15.19/bin/moc $(DEFINES) --include /Users/chenyouyuan/cyy_ws/LinkScope/moc_predefs.h -I/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/macx-clang -I/Users/chenyouyuan/cyy_ws/LinkScope -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtGui.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtNetwork.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtSerialPort.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/17/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/opt/homebrew/Cellar/qt@5/5.15.19/lib aboutwindow.h -o moc_aboutwindow.cpp

moc_configwindow.cpp: configwindow.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QDialog \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qdialog.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtSerialPort.framework/Headers/QSerialPort \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtSerialPort.framework/Headers/qserialport.h \
		moc_predefs.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/bin/moc
	/opt/homebrew/Cellar/qt@5/5.15.19/bin/moc $(DEFINES) --include /Users/chenyouyuan/cyy_ws/LinkScope/moc_predefs.h -I/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/macx-clang -I/Users/chenyouyuan/cyy_ws/LinkScope -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtGui.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtNetwork.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtSerialPort.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/17/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/opt/homebrew/Cellar/qt@5/5.15.19/lib configwindow.h -o moc_configwindow.cpp

moc_gdbprocess.cpp: gdbprocess.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QObject \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qobject.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QProcess \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qprocess.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qcoreapplication.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qfile.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qregexp.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qdebug.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QTime \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qdatetime.h \
		moc_predefs.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/bin/moc
	/opt/homebrew/Cellar/qt@5/5.15.19/bin/moc $(DEFINES) --include /Users/chenyouyuan/cyy_ws/LinkScope/moc_predefs.h -I/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/macx-clang -I/Users/chenyouyuan/cyy_ws/LinkScope -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtGui.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtNetwork.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtSerialPort.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/17/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/opt/homebrew/Cellar/qt@5/5.15.19/lib gdbprocess.h -o moc_gdbprocess.cpp

moc_graphwindow.cpp: graphwindow.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QWidget \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qwidget.h \
		vartype.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qtimer.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtGui.framework/Headers/QKeyEvent \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtGui.framework/Headers/qevent.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtGui.framework/Headers/QPainter \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtGui.framework/Headers/qpainter.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qdebug.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qmessagebox.h \
		moc_predefs.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/bin/moc
	/opt/homebrew/Cellar/qt@5/5.15.19/bin/moc $(DEFINES) --include /Users/chenyouyuan/cyy_ws/LinkScope/moc_predefs.h -I/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/macx-clang -I/Users/chenyouyuan/cyy_ws/LinkScope -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtGui.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtNetwork.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtSerialPort.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/17/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/opt/homebrew/Cellar/qt@5/5.15.19/lib graphwindow.h -o moc_graphwindow.cpp

moc_helpwindow.cpp: helpwindow.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QDialog \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qdialog.h \
		moc_predefs.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/bin/moc
	/opt/homebrew/Cellar/qt@5/5.15.19/bin/moc $(DEFINES) --include /Users/chenyouyuan/cyy_ws/LinkScope/moc_predefs.h -I/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/macx-clang -I/Users/chenyouyuan/cyy_ws/LinkScope -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtGui.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtNetwork.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtSerialPort.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/17/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/opt/homebrew/Cellar/qt@5/5.15.19/lib helpwindow.h -o moc_helpwindow.cpp

moc_listwindow.cpp: listwindow.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QWidget \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qwidget.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qprocess.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qfile.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QTime \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qdatetime.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qdebug.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtGui.framework/Headers/QStandardItem \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtGui.framework/Headers/qstandarditemmodel.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qmessagebox.h \
		gdbprocess.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QObject \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qobject.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QProcess \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qcoreapplication.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qregexp.h \
		moc_predefs.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/bin/moc
	/opt/homebrew/Cellar/qt@5/5.15.19/bin/moc $(DEFINES) --include /Users/chenyouyuan/cyy_ws/LinkScope/moc_predefs.h -I/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/macx-clang -I/Users/chenyouyuan/cyy_ws/LinkScope -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtGui.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtNetwork.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtSerialPort.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/17/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/opt/homebrew/Cellar/qt@5/5.15.19/lib listwindow.h -o moc_listwindow.cpp

moc_logwindow.cpp: logwindow.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QWidget \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qwidget.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtGui.framework/Headers/qstandarditemmodel.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qscrollbar.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QTime \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qdatetime.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qdebug.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qfile.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qfiledialog.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qmessagebox.h \
		moc_predefs.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/bin/moc
	/opt/homebrew/Cellar/qt@5/5.15.19/bin/moc $(DEFINES) --include /Users/chenyouyuan/cyy_ws/LinkScope/moc_predefs.h -I/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/macx-clang -I/Users/chenyouyuan/cyy_ws/LinkScope -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtGui.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtNetwork.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtSerialPort.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/17/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/opt/homebrew/Cellar/qt@5/5.15.19/lib logwindow.h -o moc_logwindow.cpp

moc_mainwindow.cpp: mainwindow.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QMainWindow \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qmainwindow.h \
		vartype.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QWidget \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qwidget.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qprocess.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qdebug.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QTime \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qdatetime.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QDir \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qdir.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qfiledialog.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qmessagebox.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtGui.framework/Headers/qstandarditemmodel.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qtimer.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtGui.framework/Headers/QKeyEvent \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtGui.framework/Headers/qevent.h \
		graphwindow.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtGui.framework/Headers/QPainter \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtGui.framework/Headers/qpainter.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qelapsedtimer.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qcolordialog.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qsettings.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qregexp.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtGui.framework/Headers/qdesktopservices.h \
		listwindow.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qfile.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtGui.framework/Headers/QStandardItem \
		gdbprocess.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QObject \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qobject.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QProcess \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qcoreapplication.h \
		helpwindow.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QDialog \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qdialog.h \
		aboutwindow.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtNetwork.framework/Headers/qnetworkaccessmanager.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtNetwork.framework/Headers/qnetworkreply.h \
		openocd.h \
		serialocd.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtNetwork.framework/Headers/qtcpserver.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtNetwork.framework/Headers/qtcpsocket.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QRegExp \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtSerialPort.framework/Headers/qserialport.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtSerialPort.framework/Headers/qserialportinfo.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qthread.h \
		logwindow.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qscrollbar.h \
		configwindow.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtSerialPort.framework/Headers/QSerialPort \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QCheckBox \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qcheckbox.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QLineEdit \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qlineedit.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QPushButton \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QHBoxLayout \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QDockWidget \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qdockwidget.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QJsonDocument \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qjsondocument.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QJsonObject \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qjsonobject.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QJsonArray \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qjsonarray.h \
		moc_predefs.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/bin/moc
	/opt/homebrew/Cellar/qt@5/5.15.19/bin/moc $(DEFINES) --include /Users/chenyouyuan/cyy_ws/LinkScope/moc_predefs.h -I/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/macx-clang -I/Users/chenyouyuan/cyy_ws/LinkScope -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtGui.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtNetwork.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtSerialPort.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/17/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/opt/homebrew/Cellar/qt@5/5.15.19/lib mainwindow.h -o moc_mainwindow.cpp

moc_openocd.cpp: openocd.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QObject \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qobject.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QProcess \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qprocess.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qcoreapplication.h \
		moc_predefs.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/bin/moc
	/opt/homebrew/Cellar/qt@5/5.15.19/bin/moc $(DEFINES) --include /Users/chenyouyuan/cyy_ws/LinkScope/moc_predefs.h -I/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/macx-clang -I/Users/chenyouyuan/cyy_ws/LinkScope -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtGui.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtNetwork.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtSerialPort.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/17/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/opt/homebrew/Cellar/qt@5/5.15.19/lib openocd.h -o moc_openocd.cpp

moc_serialocd.cpp: serialocd.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QObject \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qobject.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtNetwork.framework/Headers/qtcpserver.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtNetwork.framework/Headers/qtcpsocket.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QRegExp \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qregexp.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtSerialPort.framework/Headers/qserialport.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtSerialPort.framework/Headers/qserialportinfo.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qthread.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QTime \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qdatetime.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qtimer.h \
		moc_predefs.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/bin/moc
	/opt/homebrew/Cellar/qt@5/5.15.19/bin/moc $(DEFINES) --include /Users/chenyouyuan/cyy_ws/LinkScope/moc_predefs.h -I/opt/homebrew/Cellar/qt@5/5.15.19/mkspecs/macx-clang -I/Users/chenyouyuan/cyy_ws/LinkScope -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtGui.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtNetwork.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtSerialPort.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/17/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/opt/homebrew/Cellar/qt@5/5.15.19/lib serialocd.h -o moc_serialocd.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_aboutwindow.h ui_configwindow.h ui_graphwindow.h ui_helpwindow.h ui_listwindow.h ui_logwindow.h ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_aboutwindow.h ui_configwindow.h ui_graphwindow.h ui_helpwindow.h ui_listwindow.h ui_logwindow.h ui_mainwindow.h
ui_aboutwindow.h: aboutwindow.ui \
		/opt/homebrew/Cellar/qt@5/5.15.19/bin/uic
	/opt/homebrew/Cellar/qt@5/5.15.19/bin/uic aboutwindow.ui -o ui_aboutwindow.h

ui_configwindow.h: configwindow.ui \
		/opt/homebrew/Cellar/qt@5/5.15.19/bin/uic
	/opt/homebrew/Cellar/qt@5/5.15.19/bin/uic configwindow.ui -o ui_configwindow.h

ui_graphwindow.h: graphwindow.ui \
		/opt/homebrew/Cellar/qt@5/5.15.19/bin/uic
	/opt/homebrew/Cellar/qt@5/5.15.19/bin/uic graphwindow.ui -o ui_graphwindow.h

ui_helpwindow.h: helpwindow.ui \
		/opt/homebrew/Cellar/qt@5/5.15.19/bin/uic
	/opt/homebrew/Cellar/qt@5/5.15.19/bin/uic helpwindow.ui -o ui_helpwindow.h

ui_listwindow.h: listwindow.ui \
		/opt/homebrew/Cellar/qt@5/5.15.19/bin/uic
	/opt/homebrew/Cellar/qt@5/5.15.19/bin/uic listwindow.ui -o ui_listwindow.h

ui_logwindow.h: logwindow.ui \
		/opt/homebrew/Cellar/qt@5/5.15.19/bin/uic
	/opt/homebrew/Cellar/qt@5/5.15.19/bin/uic logwindow.ui -o ui_logwindow.h

ui_mainwindow.h: mainwindow.ui \
		/opt/homebrew/Cellar/qt@5/5.15.19/bin/uic
	/opt/homebrew/Cellar/qt@5/5.15.19/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

aboutwindow.o: aboutwindow.cpp aboutwindow.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QDialog \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qdialog.h \
		ui_aboutwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o aboutwindow.o aboutwindow.cpp

configwindow.o: configwindow.cpp configwindow.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QDialog \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qdialog.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtSerialPort.framework/Headers/QSerialPort \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtSerialPort.framework/Headers/qserialport.h \
		ui_configwindow.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o configwindow.o configwindow.cpp

gdbprocess.o: gdbprocess.cpp gdbprocess.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QObject \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qobject.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QProcess \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qprocess.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qcoreapplication.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qfile.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qregexp.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qdebug.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QTime \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qdatetime.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QDir \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qdir.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gdbprocess.o gdbprocess.cpp

graphwindow.o: graphwindow.cpp graphwindow.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QWidget \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qwidget.h \
		vartype.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qtimer.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtGui.framework/Headers/QKeyEvent \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtGui.framework/Headers/qevent.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtGui.framework/Headers/QPainter \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtGui.framework/Headers/qpainter.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qdebug.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qmessagebox.h \
		ui_graphwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o graphwindow.o graphwindow.cpp

helpwindow.o: helpwindow.cpp helpwindow.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QDialog \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qdialog.h \
		ui_helpwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o helpwindow.o helpwindow.cpp

listwindow.o: listwindow.cpp listwindow.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QWidget \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qwidget.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qprocess.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qfile.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QTime \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qdatetime.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qdebug.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtGui.framework/Headers/QStandardItem \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtGui.framework/Headers/qstandarditemmodel.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qmessagebox.h \
		gdbprocess.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QObject \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qobject.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QProcess \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qcoreapplication.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qregexp.h \
		ui_listwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o listwindow.o listwindow.cpp

logwindow.o: logwindow.cpp logwindow.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QWidget \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qwidget.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtGui.framework/Headers/qstandarditemmodel.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qscrollbar.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QTime \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qdatetime.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qdebug.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qfile.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qfiledialog.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qmessagebox.h \
		ui_logwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o logwindow.o logwindow.cpp

main.o: main.cpp mainwindow.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QMainWindow \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qmainwindow.h \
		vartype.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QWidget \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qwidget.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qprocess.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qdebug.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QTime \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qdatetime.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QDir \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qdir.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qfiledialog.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qmessagebox.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtGui.framework/Headers/qstandarditemmodel.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qtimer.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtGui.framework/Headers/QKeyEvent \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtGui.framework/Headers/qevent.h \
		graphwindow.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtGui.framework/Headers/QPainter \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtGui.framework/Headers/qpainter.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qelapsedtimer.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qcolordialog.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qsettings.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qregexp.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtGui.framework/Headers/qdesktopservices.h \
		listwindow.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qfile.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtGui.framework/Headers/QStandardItem \
		gdbprocess.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QObject \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qobject.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QProcess \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qcoreapplication.h \
		helpwindow.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QDialog \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qdialog.h \
		aboutwindow.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtNetwork.framework/Headers/qnetworkaccessmanager.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtNetwork.framework/Headers/qnetworkreply.h \
		openocd.h \
		serialocd.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtNetwork.framework/Headers/qtcpserver.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtNetwork.framework/Headers/qtcpsocket.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QRegExp \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtSerialPort.framework/Headers/qserialport.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtSerialPort.framework/Headers/qserialportinfo.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qthread.h \
		logwindow.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qscrollbar.h \
		configwindow.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtSerialPort.framework/Headers/QSerialPort \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QCheckBox \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qcheckbox.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QLineEdit \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qlineedit.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QPushButton \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QHBoxLayout \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QDockWidget \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qdockwidget.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QJsonDocument \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qjsondocument.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QJsonObject \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qjsonobject.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QJsonArray \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qjsonarray.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QApplication \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QMainWindow \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qmainwindow.h \
		vartype.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QWidget \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qwidget.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qprocess.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qdebug.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QTime \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qdatetime.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QDir \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qdir.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qfiledialog.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qmessagebox.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtGui.framework/Headers/qstandarditemmodel.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qtimer.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtGui.framework/Headers/QKeyEvent \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtGui.framework/Headers/qevent.h \
		graphwindow.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtGui.framework/Headers/QPainter \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtGui.framework/Headers/qpainter.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qelapsedtimer.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qcolordialog.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qsettings.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qregexp.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtGui.framework/Headers/qdesktopservices.h \
		listwindow.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qfile.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtGui.framework/Headers/QStandardItem \
		gdbprocess.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QObject \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qobject.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QProcess \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qcoreapplication.h \
		helpwindow.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QDialog \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qdialog.h \
		aboutwindow.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtNetwork.framework/Headers/qnetworkaccessmanager.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtNetwork.framework/Headers/qnetworkreply.h \
		openocd.h \
		serialocd.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtNetwork.framework/Headers/qtcpserver.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtNetwork.framework/Headers/qtcpsocket.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QRegExp \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtSerialPort.framework/Headers/qserialport.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtSerialPort.framework/Headers/qserialportinfo.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qthread.h \
		logwindow.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qscrollbar.h \
		configwindow.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtSerialPort.framework/Headers/QSerialPort \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QCheckBox \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qcheckbox.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QLineEdit \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qlineedit.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QPushButton \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QHBoxLayout \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/QDockWidget \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtWidgets.framework/Headers/qdockwidget.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QJsonDocument \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qjsondocument.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QJsonObject \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qjsonobject.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QJsonArray \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qjsonarray.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

openocd.o: openocd.cpp openocd.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QObject \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qobject.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QProcess \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qprocess.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qcoreapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o openocd.o openocd.cpp

serialocd.o: serialocd.cpp serialocd.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QObject \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qobject.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtNetwork.framework/Headers/qtcpserver.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtNetwork.framework/Headers/qtcpsocket.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QRegExp \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qregexp.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtSerialPort.framework/Headers/qserialport.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtSerialPort.framework/Headers/qserialportinfo.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qthread.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/QTime \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qdatetime.h \
		/opt/homebrew/Cellar/qt@5/5.15.19/lib/QtCore.framework/Headers/qtimer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o serialocd.o serialocd.cpp

qrc_res.o: qrc_res.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_res.o qrc_res.cpp

moc_aboutwindow.o: moc_aboutwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_aboutwindow.o moc_aboutwindow.cpp

moc_configwindow.o: moc_configwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_configwindow.o moc_configwindow.cpp

moc_gdbprocess.o: moc_gdbprocess.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_gdbprocess.o moc_gdbprocess.cpp

moc_graphwindow.o: moc_graphwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_graphwindow.o moc_graphwindow.cpp

moc_helpwindow.o: moc_helpwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_helpwindow.o moc_helpwindow.cpp

moc_listwindow.o: moc_listwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_listwindow.o moc_listwindow.cpp

moc_logwindow.o: moc_logwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_logwindow.o moc_logwindow.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_openocd.o: moc_openocd.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_openocd.o moc_openocd.cpp

moc_serialocd.o: moc_serialocd.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_serialocd.o moc_serialocd.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/LinkScope/bin || mkdir -p $(INSTALL_ROOT)/opt/LinkScope/bin
	$(DEL_FILE) -r $(INSTALL_ROOT)/opt/LinkScope/bin/LinkScope.app
	
	$(QINSTALL) LinkScope.app $(INSTALL_ROOT)/opt/LinkScope/bin/LinkScope.app
	-$(STRIP) $(INSTALL_ROOT)/opt/LinkScope/bin/LinkScope.app/Contents/MacOS/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/LinkScope/bin/LinkScope.app
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/LinkScope/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

